### ISSUE TITLE
for loop vs forEach

### ISSUE THREAD

**Issue by sultanassi95** [facg3/JokeGenerator#13]
https://github.com/facg3/JokeGenerator/blob/70cbf8c05e5a0a568aba3f6189d471ad7e000443/public/index.js#L13

you should use Array.forEach instead of for, it does the same job, but for loops are considered to be expensive.
[Read More](https://thejsguy.com/2016/07/30/javascript-for-loop-vs-array-foreach.html)

**Comment by MMortaga** [comment]
Well, you're right.
queryselector does return an array and we could've used forEach.. but guess a tiny for loop seemed a bit simpler.

**Comment by sultanassi95** [comment]
it is simpler, yeap, but imagine a code having a 100 for loops, each one has a LOOP COUNTER (in this case it's: i) , then you will be declaring un-necessary 100 counter variables!
for this project it's totally fine i guess, but just as a future reminder ^_^
