### ISSUE TITLE
unused files.

### ISSUE THREAD

**Issue by sultanassi95** [facg3/JokeGenerator#21]
uploading unnecessary files along with your project to github repos is not cool at all, try making sure that you only upload what's needed to make your project work, also, at your machine, you only should have a clear structure that has a clear list of your files.

for:
JokeGenerator/public/1.jpg
JokeGenerator/faces.js

**Comment by hananqwaider** [comment]
we deleted them @sultanassi95  thx

**Comment by sultanassi95** [comment]
I checked the master branch, but they are still there, hmmm, can you re check?
