### ISSUE TITLE
Think of abetter way to handle your errors

### ISSUE THREAD

**Issue by Eslam3bed** [facg3/JokeGenerator#25]
https://github.com/facg3/JokeGenerator/blob/70cbf8c05e5a0a568aba3f6189d471ad7e000443/src/handler.js#L42

> maybe sending them back to let your users know what's going on in the backend ^_^

**Comment by MMortaga** [comment]
Yeah. We're gonna fix that in a moment :)

**Comment by MMortaga** [comment]
done.

**Comment by Eslam3bed** [comment]
Pls , Rase a reference to the changes so I can easily see it 
it's a good practice ^_^

and mack sure to solve the conflicts before merging :+1:
